version: '3.8'
services:
  db:
    build: .
    restart: always
    environment:
      POSTGRES_USER: "${PGUSER:-postgres}"
      POSTGRES_PASSWORD: "${PGPASSWORD:-password}"
      POSTGIS_GDAL_ENABLED_DRIVERS: 'GTiff PNG SNODAS'
    ports:
      - '${PGPORT:-5432}:5432'
