# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-30 00:31
from __future__ import unicode_literals

import os

from django.db import migrations


with open(
    os.path.join(
        os.path.dirname(__file__),
        'sql',
        os.path.splitext(os.path.basename(__file__))[0] + '.sql',
    )
) as sqlfile:
    sql = sqlfile.read()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
                sql
            )
    ]
